### ISSUE TITLE
`gap` on Flex in not working as expected

### ISSUE THREAD

**Issue by AWIXOR-zz** [smakosh/react-flex-ready#21]
If I set the `gap` for Flex, I am expecting my div to have a CSS property `gap` set to a specific value.

**Comment by smakosh** [comment]
`gap` is meant to be set on `Item` actually.

**Comment by AWIXOR-zz** [comment]
It would be great if added to `Flex` too, so instead of setting margins, you can just set a `gap` between Items.

**Comment by smakosh** [comment]
I'll think of it and see if there are use cases for it

**Comment by AWIXOR-zz** [comment]
If you decided to add it, I can work on it.
